package org.fhir.ucum;



import org.junit.jupiter.api.Test;

import java.util.*;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;

public class UcumCommonUnitsTest extends UcumServiceTest
{
    static class CommonUnit
    {
        final String unit;
        final String dim;   // not really using this
        final String can;   // canonical unit

        CommonUnit(String unit, String dim)
        {
            this.unit = unit;
            this.dim = dim;
            this.can = null;
        }

        CommonUnit(String unit, String dim, String can)
        {
            this.unit = unit;
            this.dim = dim;
            this.can = can;
        }
    }


    @Test
    public void analyze() throws UcumException
    {
        for (CommonUnit cu : units)
        {
            ucumService.analyse(cu.unit);
        }
    }


    @Test
    public void canonical() throws UcumException
    {
        Set<String> set = new HashSet<>();
        for (CommonUnit cu : units)
        {
            // BUG?
            if ("dB".equals(cu.unit))
                continue;
            String can = ucumService.getCanonicalUnits(cu.unit);
            if (null != cu.can)
                assertEquals(cu.can, can,cu.unit);
            else if (set.add(cu.dim+" -> "+can) && cu.dim != null)
                System.out.println(cu.dim+" -> "+can + "\t\t" + cu.unit);
        }
    }


    @Test
    public void convert() throws UcumException
    {
        Decimal ONE = new Decimal("1",15);
        for (CommonUnit cu : units)
        {
            // BUG: avoid NPE
            if ("Cel".equals(cu.unit) || "[degF]".equals(cu.unit) || "[pH]".equals(cu.unit))
                continue;
            // maybe bug? avoid UnumException
            if ("dB".equals(cu.unit))
                continue;
            try
            {
                String can = ucumService.getCanonicalUnits(cu.unit);
                if (null != can && !"".equals(can))
                    ucumService.convert(ONE, cu.unit, can);
            }
            catch (Exception x)
            {
                fail(cu.unit + ": " + x.getMessage());
            }
        }
    }


    @Test
    public void convert2() throws UcumException
    {
        Map<String, List<CommonUnit>> map = new HashMap<>();
        for (CommonUnit cu : units)
        {
            // BUG?
            if ("dB".equals(cu.unit))
                continue;
            String can = ucumService.getCanonicalUnits(cu.unit);
            if (null == can || "".equals(can))
                continue;
            if (!map.containsKey(can))
                map.put(can, new ArrayList<>());
            map.get(can).add(cu);
        }
        for (String can : map.keySet())
        {
            List<CommonUnit> list = map.get(can);
            convertAll(list);
        }
    }


    private void convertAll(List<CommonUnit> list) throws UcumException
    {
        Decimal K = new Decimal("2.3", 15);
        for (CommonUnit a : list)
        {
            for (CommonUnit b : list)
            {
                try
                {
                    // BUG?
                    if ("[pH]".equals(a.unit))
                        continue;
                    if ("Cel".equals(a.unit) || "[degF]".equals(a.unit))
                        continue;
                    ucumService.convert(K, a.unit, b.unit);
                }
                catch (Exception x)
                {
                    System.out.println(a.unit + "->" + b.unit + " : " + (x.getMessage()==null ? x.toString() : x.getMessage()));
                }
            }
        }
    }


    //@Test
    public void duplicates()
    {
        HashSet<String> set = new HashSet<>();
        for (CommonUnit cu : units)
        {
            if (!set.add(cu.unit))
                System.out.println("DUPLICATE: " + cu.unit);
        }
    }


    // Commonly Used UCM Codes (sorted to remove duplicates, not for readability)
    static final List<CommonUnit> units = Collections.unmodifiableList(Arrays.asList(   // List.of()
        new CommonUnit("%{0to3Hours}", "1"),
        new CommonUnit("%", "1"),
        new CommonUnit("/100", "1"),
        new CommonUnit("/100{cells}", null),
        new CommonUnit("/100{neutrophils}", null),
        new CommonUnit("/100{Spermatozoa}", "1"),
        new CommonUnit("%/100{WBC}", "1"),
        new CommonUnit("/100{WBC}", "1"),
        new CommonUnit("/100{WBCs}", null),
        new CommonUnit("/10*10", "1"),
        new CommonUnit("/10*12", "1"),
        new CommonUnit("10*12/L", "L-17", "m-3"),
        new CommonUnit("/10*12{rbc}", "1"),
        new CommonUnit("/10*12{RBCs}", null),
        new CommonUnit("10*3", "1"),
        new CommonUnit("10*3{Copies}/mL", "L-9", "m-3"),
        new CommonUnit("10*3{copies}/mL", null),
        new CommonUnit("10*3/L", "L-15", "m-3"),
        new CommonUnit("10*3/mL", "L-8", "m-3"),
        new CommonUnit("/10*3", null),
        new CommonUnit("10*3.{RBC}", "1"),
        new CommonUnit("/10*3{RBCs}", null),
        new CommonUnit("10*3{RBCs}", null),
        new CommonUnit("10*3/uL", "L-3", "m-3"),
        new CommonUnit("/10*4{RBCs}", null),
        new CommonUnit("10*4/uL", null),
        new CommonUnit("10*5", "1"),
        new CommonUnit("/10*6", "1"),
        new CommonUnit("10*6", "1"),
        new CommonUnit("10*6/(24.h)", null),
        new CommonUnit("10*6.[CFU]/L", null),
        new CommonUnit("10*6.eq/mL", "L-3N", "m-3"),
        new CommonUnit("10*6.[iU]", "[arb]"),
        new CommonUnit("10*6.[IU]", null),
        new CommonUnit("10*6/kg", null),
        new CommonUnit("10*6/L", "L-16", "m-3"),
        new CommonUnit("10*6/mL", "L-10", "m-3"),
        new CommonUnit("10*6/{Specimen}", "1"),
        new CommonUnit("10*6/uL", "L-3", "m-3"),
        new CommonUnit("10*8", "1"),
        new CommonUnit("/10*9", "1"),
        new CommonUnit("10*9/L", "L-18", "m-3"),
        new CommonUnit("10*9/mL", "L-11", "m-3"),
        new CommonUnit("10*9/uL", "L-4", "m-3"),
        new CommonUnit("10.L/(min.m2)", null),
        new CommonUnit("10.L/min", null),
        new CommonUnit("10.uN.s/(cm5.m2)", null),
        new CommonUnit("/(12.h)", null),
        new CommonUnit("24.h", null),
        new CommonUnit("%{Abnormal}", "1"),
        new CommonUnit("%{abnormal}", null),
        new CommonUnit("{absorbance}", null),
        new CommonUnit("%{Activity}", "1"),
        new CommonUnit("%{activity}", null),
        new CommonUnit("{activity}", null),
        new CommonUnit("ag/{cell}", null),
        new CommonUnit("%{aggregation}", null),
        new CommonUnit("{AHF'U}", null),
        new CommonUnit("A/m", null),
        new CommonUnit("/a", null),
        new CommonUnit("{#}/a", null),
        new CommonUnit("A", null),
        new CommonUnit("[APL'U]/mL", null),
        new CommonUnit("[APL'U]", null),
        new CommonUnit("{APS'U}", null),
        new CommonUnit("/[arb'U]", "[arb]-1"),
        new CommonUnit("[arb'U]/mL", null),
        new CommonUnit("{ARU}", null),
        new CommonUnit("a", "T", "s"),
        new CommonUnit("%{at_60_min}", null),
        new CommonUnit("atm", null),
        new CommonUnit("[AU]", null),
        new CommonUnit("%{bacteria}", null),
        new CommonUnit("bar", null),
        new CommonUnit("%{BasalActivity}", "1"),
        new CommonUnit("%{basal_activity}", null),
        new CommonUnit("%{baseline}", null),
        new CommonUnit("[bdsk'U]", null),
        new CommonUnit("{beats}/min", null),
        new CommonUnit("[beth'U]", null),
        new CommonUnit("%{Binding}", "1"),
        new CommonUnit("{binding_index}", null),
        new CommonUnit("%{binding}", null),
        new CommonUnit("%{Blockade}", "1"),
        new CommonUnit("%{blockade}", null),
        new CommonUnit("%{blocked}", null),
        new CommonUnit("%{Bound}", "1"),
        new CommonUnit("%{bound}", null),
        new CommonUnit("Bq", null),
        new CommonUnit("%{breakdown}", null),
        new CommonUnit("{breaths}/min", null),
        new CommonUnit("{CAE'U}", null),
        new CommonUnit("{CAG_repeats}", null),
        new CommonUnit("cal", null),
        new CommonUnit("%{Carboxyhemoglobin}", "1"),
        new CommonUnit("{cells}/[HPF]", null),
        new CommonUnit("%{cells}", null),
        new CommonUnit("{cells}", null),
        new CommonUnit("{Cells}/uL", "L-3", "m-3"),
        new CommonUnit("{cells}/uL", null),
//        new CommonUnit("Cel", "q", "K"),
        new CommonUnit("[CFU]/L", null),
        new CommonUnit("{cfu}/mL", "L-12", "m-3"),
        new CommonUnit("[CFU]/mL", null),
        new CommonUnit("[CFU]", null),
        new CommonUnit("cg", "M", "g"),
        new CommonUnit("{CH100'U}", null),
        new CommonUnit("[Ch]", "L", "m"),
        new CommonUnit("[cin_i]", "L3", "m3"),
        new CommonUnit("cL", "L3", "m3"),
        new CommonUnit("{clock_time}", null),
        new CommonUnit("cm2", "L2", "m2"),
        new CommonUnit("cm2/s", null),
        new CommonUnit("cm3", null),
        new CommonUnit("cm[H2O]/L/s", null),
        new CommonUnit("/cm[H2O]", null),
        new CommonUnit("cm[H2O]", null),
        new CommonUnit("cm[H2O]/s/m", null),
        new CommonUnit("cm[Hg]", null),
        new CommonUnit("cm", "L", "m"),
        new CommonUnit("cm/s", null),
        new CommonUnit("{Copies}/mL", "L-7", "m-3"),
        new CommonUnit("{copies}/mL", null),
        new CommonUnit("{copies}", null),
        new CommonUnit("{copies}/ug", null),
        new CommonUnit("{count}", null),
        new CommonUnit("{CPM}/10*3{cell}", null),
        new CommonUnit("{CPM}", null),
        new CommonUnit("cP", null),
        new CommonUnit("cSt", null),
        new CommonUnit("{Ct_value}", null),
        new CommonUnit("[cup_us]", "L3", "m3"),
        new CommonUnit("d/(7.d)", null),
        new CommonUnit("daL/min/m2", null),
        new CommonUnit("daL/min", null),
        new CommonUnit("dB", null),
        new CommonUnit("%{deficient}", null),
        new CommonUnit("deg", "1", "rad"),
//        new CommonUnit("[degF]", "q", "K"),
        new CommonUnit("deg/s", null),
        new CommonUnit("{delta_OD}", null),
        new CommonUnit("dg", "M", "g"),
        new CommonUnit("{dilution}", null),
        new CommonUnit("[diop]", null),
        new CommonUnit("/dL", "L-13", "m-3"),
        new CommonUnit("dL", "L3", "m3"),
        new CommonUnit("dm2/s2", null),
        new CommonUnit("dm", "L", "m"),
        new CommonUnit("/d", null),
        new CommonUnit("{#}/d", null),
        new CommonUnit("%{dose}", null),
        new CommonUnit("[dr_av]", "M", "g"),
        new CommonUnit("[drp]", null),
        new CommonUnit("d", "T", "s"),
        new CommonUnit("d/wk", null),
        new CommonUnit("dyn.s/(cm.m2)", null),
        new CommonUnit("dyn.s/cm", null),
        new CommonUnit("{Ehrlich_U}/100.g", "M-1[arb]"),
        new CommonUnit("{Ehrlich'U}/100.g", null),
        new CommonUnit("{Ehrlich'U}/(2.h)", null),
        new CommonUnit("{Ehrlich_U}/dL", "L-3[arb]", "m-3"),
        new CommonUnit("{Ehrlich'U}/dL", null),
        new CommonUnit("{Ehrlich'U}/d", null),
        new CommonUnit("{Ehrlich'U}", null),
        new CommonUnit("{EIA_index}", null),
        new CommonUnit("{EIA_titer}", null),
        new CommonUnit("{EIA'U}", null),
        new CommonUnit("{EIA'U}/U", null),
        new CommonUnit("{Elisa_U}/mL", "L-3[arb]", "m-3"),
        new CommonUnit("{ELISA'U}", null),
        new CommonUnit("/{Entity}", "1"),
        new CommonUnit("/{entity}", null),
        new CommonUnit("%{EosSeen}", "1"),
        new CommonUnit("eq{AHG}/mL", "L-3N", "m-3"),
        new CommonUnit("eq{BoneCollagen}/mmol{Cre}", "1"),
        new CommonUnit("eq{BoneCollagen}/umol{Cre}", "1"),
        new CommonUnit("eq/L", "L-3N", "m-3"),
        new CommonUnit("eq/mL", "L-3N", "m-3"),
        new CommonUnit("eq/mmol", "1"),
        new CommonUnit("eq", "N"),
        new CommonUnit("eq/umol", "1"),
        new CommonUnit("erg", null),
        new CommonUnit("eV", null),
        new CommonUnit("{EV}", null),
        new CommonUnit("%{Excretion}", "1"),
        new CommonUnit("%{excretion}", null),
        new CommonUnit("[fdr_us]", "L3", "m3"),
        new CommonUnit("%{FetalErythrocytes}", "1"),
        new CommonUnit("fg", "M", "g"),
        new CommonUnit("{FIU}", null),
        new CommonUnit("fL", "L3", "m3"),
        new CommonUnit("fm", "L", "m"),
        new CommonUnit("fmol/g", "M-1N", "g-1"),
        new CommonUnit("fmol/L", null),
        new CommonUnit("fmol/mg{cyt_prot}", null),
        new CommonUnit("fmol/mg", "M-1N"),
        new CommonUnit("fmol/mg{prot}", null),
        new CommonUnit("fmol/mL", "L-3N", "m-3"),
        new CommonUnit("fmol", "N"),
        new CommonUnit("F", null),
        new CommonUnit("[foz_us]", "L3", "m3"),
        new CommonUnit("{fraction}", null),
        new CommonUnit("[fth_i]", "L", "m"),
        new CommonUnit("[ft_i]", "L", "m"),
        new CommonUnit("[ft_us]/[ft_us]", null),
        new CommonUnit("g/(100.g)", null),
        new CommonUnit("g/(12.h)", null),
        new CommonUnit("g/(24.h)", null),
        new CommonUnit("g/(3.d)", null),
        new CommonUnit("g/(48.h)", null),
        new CommonUnit("g/(4.h)", null),
        new CommonUnit("g/(5.h)", null),
        new CommonUnit("g/(6.h)", null),
        new CommonUnit("g/(72.h)", null),
        new CommonUnit("g/(8.h){shift}", null),
        new CommonUnit("{GAA_repeats}", null),
        new CommonUnit("[gal_us]", "L3", "m3"),
        new CommonUnit("g/cm2", null),
        new CommonUnit("g/cm3", null),
        new CommonUnit("/g{creat}", "M-1", "g-1"),
        new CommonUnit("g{creat}", null),
        new CommonUnit("g/dL", "L-3M", "g.m-3"),
        new CommonUnit("g/d", null),
        new CommonUnit("{genomes}/mL", null),
        new CommonUnit("g/g", "1"),
        new CommonUnit("g/g{Cre}", "1"),
        new CommonUnit("g/g{creat}", null),
        new CommonUnit("g/g{globulin}", null),
        new CommonUnit("g/g{tissue}", null),
        new CommonUnit("/g{Hb}", null),
        new CommonUnit("g{Hb}", null),
        new CommonUnit("/g{HGB}", "M-1", "g-1"),
        new CommonUnit("g/h/m2", null),
        new CommonUnit("g/h", null),
        new CommonUnit("g/kg", "1"),
        new CommonUnit("g/kg/(8.h)", null),
        new CommonUnit("g/kg/(8.h){shift}", null),
        new CommonUnit("g/kg/d", null),
        new CommonUnit("g/kg/h", null),
        new CommonUnit("g/kg/min", null),
        new CommonUnit("g/L", "L-3M", "g.m-3"),
        new CommonUnit("{Globules}/[HPF]", null),
        new CommonUnit("/g", "M-1", "g-1"),
        new CommonUnit("g/m2", "L-2M", "g.m-2"),
        new CommonUnit("g.m/{beat}", null),
        new CommonUnit("g", "M", "g"),
        new CommonUnit("g/mg", null),
        new CommonUnit("g.m/{hb}", "LM", "g.m"),
        new CommonUnit("g.m/({hb}.m2)", "L-1M"),
        new CommonUnit("g/min", null),
        new CommonUnit("g/mL", "L-3M", "g.m-3"),
        new CommonUnit("g.m", "LM", "g.m"),
        new CommonUnit("g/mmol", null),
        new CommonUnit("g/mol{creat}", null),
        new CommonUnit("{#}/g", null),
        new CommonUnit("[GPL'U]/mL", null),
        new CommonUnit("[GPL'U]", null),
        new CommonUnit("{GPS'U}", null),
        new CommonUnit("[gr]", "M", "g"),
        new CommonUnit("g/{specimen}", null),
        new CommonUnit("g{total_nit}", null),
        new CommonUnit("g/{total_output}", null),
        new CommonUnit("g{total_prot}", null),
        new CommonUnit("g/{TotalWeight}", "M", "g"),
        new CommonUnit("g/{total_weight}", null),
        new CommonUnit("/g{tot`nit}", "M-1", "g-1"),
        new CommonUnit("/g{tot_nit}", null),
        new CommonUnit("/g{tot`prot}", "M-1", "g-1"),
        new CommonUnit("/g{tot_prot}", null),
        new CommonUnit("/g{wet`tis}", "M-1", "g-1"),
        new CommonUnit("/g{wet_tis}", null),
        new CommonUnit("g{wet_tissue}", null),
        new CommonUnit("Gy", null),
        new CommonUnit("{HA_titer}", null),
        new CommonUnit("%{Hb}", null),
        new CommonUnit("h/d", null),
        new CommonUnit("%{Hemoglobin}", "1"),
        new CommonUnit("%{HemoglobinA1C}", "1"),
        new CommonUnit("%{HemoglobinSaturation}", "1"),
        new CommonUnit("%{Hemolysis}", "1"),
        new CommonUnit("%{hemolysis}", null),
        new CommonUnit("hL", "L3", "m3"),
        new CommonUnit("/h", null),
        new CommonUnit("H", null),
        new CommonUnit("/[HPF]", null),
        new CommonUnit("[HPF]", null),
        new CommonUnit("{#}/[HPF]", null),
        new CommonUnit("h", "T", "s"),
        new CommonUnit("h/wk", null),
        new CommonUnit("Hz", null),
        new CommonUnit("{IFA_index}", null),
        new CommonUnit("{IFA_titer}", null),
        new CommonUnit("{ImmuneComplex'U}", null),
        new CommonUnit("%{index}", null),
        new CommonUnit("{index}", null),
        new CommonUnit("{index_val}", null),
        new CommonUnit("%{Inhibition}", "1"),
        new CommonUnit("%{inhibition}", null),
        new CommonUnit("[in_i'H2O]", null),
        new CommonUnit("[in_i]", "L", "m"),
        new CommonUnit("{INR}", null),
        new CommonUnit("[in_us]", null),
        new CommonUnit("{ISR}", null),
        new CommonUnit("[IU]/10*9{RBCs}", null),
        new CommonUnit("[IU]/(24.h)", null),
        new CommonUnit("[IU]/(2.h)", null),
        new CommonUnit("[iU]", "[arb]"),
        new CommonUnit("[iU]/dL", "L-3[arb]", "m-3"),
        new CommonUnit("[IU]/dL", null),
        new CommonUnit("[IU]/d", null),
        new CommonUnit("[IU]/g{Hb}", null),
        new CommonUnit("[iU]/g{Hgb}", "M-1[arb]"),
        new CommonUnit("[iU]/g", "M-1[arb]"),
        new CommonUnit("[IU]/g", null),
        new CommonUnit("[IU]/h", null),
        new CommonUnit("[IU]/kg/d", null),
        new CommonUnit("[iU]/kg", "M-1[arb]"),
        new CommonUnit("[IU]/kg", null),
        new CommonUnit("[IU]/L{37Cel}", null),
        new CommonUnit("[iU]/L", "L-3[arb]", "m-3"),
        new CommonUnit("[IU]/mg{creat}", null),
        new CommonUnit("[IU]/min", null),
        new CommonUnit("[iU]/mL", "L-3[arb]", "m-3"),
        new CommonUnit("[IU]/mL", null),
        new CommonUnit("/[IU]", null),
        new CommonUnit("[IU]", null),
        new CommonUnit("{JDF'U}/L", null),
        new CommonUnit("{JDF'U}", null),
        new CommonUnit("J/L", null),
        new CommonUnit("J", null),
        new CommonUnit("kat/kg", "M-1T-1N"),
        new CommonUnit("kat/L", null),
        new CommonUnit("kat", null),
        new CommonUnit("[ka'U]", null),
        new CommonUnit("kcal/(24.h)", null),
        new CommonUnit("kcal/d", null),
        new CommonUnit("kcal/h", null),
        new CommonUnit("kcal/kg/(24.h)", null),
        new CommonUnit("kcal", null),
        new CommonUnit("kcal/[oz_av]", "L2T-2"),
        new CommonUnit("{KCT'U}", null),
        new CommonUnit("/kg{body`wt}", "M-1", "g-1"),
        new CommonUnit("/kg{body_wt}", null),
        new CommonUnit("kg/h", null),
        new CommonUnit("kg/L", "L-3M", "g.m-3"),
        new CommonUnit("/kg", "M-1", "g-1"),
        new CommonUnit("kg/m2", "L-2M", "g.m-2"),
        new CommonUnit("kg/m3", "L-3M", "g.m-3"),
        new CommonUnit("kg", "M", "g"),
        new CommonUnit("kg/min", null),
        new CommonUnit("kg/mol", "MN-1", "g"),
        new CommonUnit("kg.m/s", null),
        new CommonUnit("kg/(s.m2)", null),
        new CommonUnit("kg/s", null),
        new CommonUnit("k[IU]/L", null),
        new CommonUnit("k[iU]/mL", "L-3[arb]", "m-3"),
        new CommonUnit("k[IU]/mL", null),
        new CommonUnit("kL", "L3", "m3"),
        new CommonUnit("km", "L", "m"),
        new CommonUnit("[knk'U]", null),
        new CommonUnit("kPa", "L-1MT-2"),
        new CommonUnit("K", "q", "K"),
        new CommonUnit("{KRONU'U}/mL", null),
        new CommonUnit("ks", "T", "s"),
        new CommonUnit("kU/g", "M-1T-1N"),
        new CommonUnit("kU/L{class}", null),
        new CommonUnit("kU/L", null),
        new CommonUnit("kU/mL", null),
        new CommonUnit("kU", null),
        new CommonUnit("K/W", "L-2M-1T3q"),
        new CommonUnit("L/(24.h)", null),
        new CommonUnit("L/(8.h)", null),
        new CommonUnit("[lb_av]", "M", "g"),
        new CommonUnit("L/d", null),
        new CommonUnit("L/h", null),
        new CommonUnit("L/kg", "L3M-1", "g-1.m3"),
        new CommonUnit("/L", "L-14", "m-3"),
        new CommonUnit("L", "L3", "m3"),
        new CommonUnit("L/L", null),
        new CommonUnit("L/(min.m2)", null),
        new CommonUnit("L/min/m2", null),
        new CommonUnit("L/min", null),
        new CommonUnit("lm.m2", null),
        new CommonUnit("lm", null),
        new CommonUnit("{#}/L", null),
        new CommonUnit("{Log_copies}/mL", null),
        new CommonUnit("{Log_IU}/mL", null),
        new CommonUnit("{Log_IU}", null),
        new CommonUnit("{Log}", null),
        new CommonUnit("%{loss_AChR}", null),
        new CommonUnit("%{loss}", null),
        new CommonUnit("/[LPF]", null),
        new CommonUnit("[LPF]", null),
        new CommonUnit("{#}/[LPF]", null),
        new CommonUnit("L.s2/s", "L3T", "m3.s"),
        new CommonUnit("L/s", null, "m3.s-1"),
        new CommonUnit("L/s/s2", null),
        new CommonUnit("{Lyme_index_value}", null),
        new CommonUnit("%{lysis}", null),
        new CommonUnit("/m2", "L-2", "m-2"),
        new CommonUnit("m2", "L2", "m2"),
        new CommonUnit("m2/s", null, "m2.s-1"),
        new CommonUnit("/m3", null, "m-3"),
        new CommonUnit("m3/s", null, "m3.s-1"),
        new CommonUnit("mA", null),
        new CommonUnit("mbar/L/s", null),
        new CommonUnit("mbar", null),
        new CommonUnit("mbar.s/L", null),
        new CommonUnit("[mclg'U]", null),
        new CommonUnit("meq/(24.h)", null),
        new CommonUnit("meq/(2.h)", null),
        new CommonUnit("meq/(8.h)", null),
        new CommonUnit("meq/dL", "L-3N", "m-3"),
        new CommonUnit("meq/d", null),
        new CommonUnit("meq/g{creat}", null),
        new CommonUnit("meq/g{Cre}", "M-1N"),
        new CommonUnit("meq/g", "M-1N"),
        new CommonUnit("meq/h", null),
        new CommonUnit("meq/kg/h", null),
        new CommonUnit("meq/kg", "M-1N"),
        new CommonUnit("meq/L", "L-3N", "m-3"),
        new CommonUnit("meq/m2", "L-2N", "m-2"),
        new CommonUnit("meq/min", null),
        new CommonUnit("meq/mL", "L-3N", "m-3"),
        new CommonUnit("meq", "N"),
        new CommonUnit("meq/{Specimen}", "N"),
        new CommonUnit("meq/{specimen}", null),
        new CommonUnit("meq/{total_volume}", null),
        new CommonUnit("[MET].min/wk", null),
        new CommonUnit("mg/(10.h)", null),
        new CommonUnit("mg/(12.h)", null),
        new CommonUnit("mg/(24.h)", null),
        new CommonUnit("mg/(2.h)", null),
        new CommonUnit("mg/(6.h)", null),
        new CommonUnit("mg/(72.h)", null),
        new CommonUnit("mg/(8.h)", null),
        new CommonUnit("mg/{collection}", null),
        new CommonUnit("mg/d/{1.73_m2}", null),
        new CommonUnit("mg/dL", "L-3M", "g.m-3"),
        new CommonUnit("mg/dL{RBCs}", null),
        new CommonUnit("mg/d", null),
        new CommonUnit("mg{FEU}/L", null),
        new CommonUnit("mg/g", "1"),
        new CommonUnit("mg/g{Cre}", "1"),
        new CommonUnit("mg/g{creat}", null),
        new CommonUnit("mg/g{dry_tissue}", null),
        new CommonUnit("mg/g{feces}", null),
        new CommonUnit("mg/g{tissue}", null),
        new CommonUnit("mg/g{wet_tissue}", null),
        new CommonUnit("mg/h", null),
        new CommonUnit("mg/kg", "1"),
        new CommonUnit("mg/kg/(8.h)", null),
        new CommonUnit("mg/kg/d", null),
        new CommonUnit("mg/kg/h", null),
        new CommonUnit("mg/kg/min", null),
        new CommonUnit("mg/L", "L-3M", "g.m-3"),
        new CommonUnit("mg/L{RBCs}", null),
        new CommonUnit("/mg", "M-1", "g-1"),
        new CommonUnit("mg/m2", "L-2M", "g.m-2"),
        new CommonUnit("mg/m3", "L-3M", "g.m-3"),
        new CommonUnit("mg", "M", "g"),
        new CommonUnit("mg/mg", "1"),
        new CommonUnit("mg/mg{Cre}", "1"),
        new CommonUnit("mg/mg{creat}", null),
        new CommonUnit("mg/min", null),
        new CommonUnit("mg/mL", "L-3M", "g.m-3"),
        new CommonUnit("mg/mmol{creat}", null),
        new CommonUnit("mg/mmol", null),
        new CommonUnit("mg{Phenylketones}/dL", "L-3M", "g.m-3"),
        new CommonUnit("mg/{specimen}", null),
        new CommonUnit("mg/{total_output}", null),
        new CommonUnit("mg/{TotalVolume}", "M", "g"),
        new CommonUnit("mg/{total_volume}", null),
        new CommonUnit("mg/{Volume}", "M", "g"),
        new CommonUnit("mg/wk", null),
        new CommonUnit("[mi_i]", "L", "m"),
        new CommonUnit("min/d", null),
        new CommonUnit("{minidrop}/min", null),
        new CommonUnit("{minidrop}/s", null),
        new CommonUnit("/min", null),
        new CommonUnit("{#}/min", null),
        new CommonUnit("min", "T", "s"),
        new CommonUnit("min/wk", null),
        new CommonUnit("m[iU]/L", "L-3[arb]", "m-3"),
        new CommonUnit("m[IU]/L", null),
        new CommonUnit("m[iU]/mL", "L-3[arb]", "m-3"),
        new CommonUnit("m[IU]/mL", null),
        new CommonUnit("mL/(10.h)", null),
        new CommonUnit("mL/(12.h)", null),
        new CommonUnit("mL/(24.h)", null),
        new CommonUnit("mL/(2.h)", null),
        new CommonUnit("mL/(4.h)", null),
        new CommonUnit("mL/(5.h)", null),
        new CommonUnit("mL/(6.h)", null),
        new CommonUnit("mL/(72.h)", null),
        new CommonUnit("mL/(8.h)/kg", null),
        new CommonUnit("mL/(8.h)", null),
        new CommonUnit("mL/{beat}/m2", null),
        new CommonUnit("mL/{beat}", null),
        new CommonUnit("mL/cm[H2O]", null),
        new CommonUnit("mL/dL", "1"),
        new CommonUnit("mL/d", null),
        new CommonUnit("mL{fetal_RBCs}", null),
        new CommonUnit("mL/{h`b}", "L3", "m3"),
        new CommonUnit("mL/h", null),
        new CommonUnit("mL/kg/(8.h)", null),
        new CommonUnit("mL/kg/d", null),
        new CommonUnit("mL/kg/h", null),
        new CommonUnit("mL/kg", "L3M-1", "g-1.m3"),
        new CommonUnit("mL/kg/min", null),
        new CommonUnit("mL", "L3", "m3"),
        new CommonUnit("/mL", "L-5", "m-3"),
        new CommonUnit("m", "L", "m"),
        new CommonUnit("mL/m2", null),
        new CommonUnit("mL/mbar", null),
        new CommonUnit("mL/min/{1.73_m2}", null),
        new CommonUnit("mL/min/m2", null),
        new CommonUnit("mL/min", null),
        new CommonUnit("mL/mm", null),
        new CommonUnit("{#}/mL", null),
        new CommonUnit("mL/[sin_i]", null),
        new CommonUnit("mL/s", null),
        new CommonUnit("mm2", "L2", "m2"),
        new CommonUnit("{mm/dd/yyyy}", null),
        new CommonUnit("mm[H2O]", null),
        new CommonUnit("mm[Hg]", "L-1MT-2"),
        new CommonUnit("mm/h", null),
        new CommonUnit("mm", "L", "m"),
        new CommonUnit("mm/min", null),
        new CommonUnit("/mm", null),
        new CommonUnit("mmol/(12.h)", null),
        new CommonUnit("mmol/(24.h)", null),
        new CommonUnit("mmol/(2.h)", null),
        new CommonUnit("mmol/(5.h)", null),
        new CommonUnit("mmol/(6.h)", null),
        new CommonUnit("mmol/(8.h)", null),
        new CommonUnit("/mmol{creat}", null),
        new CommonUnit("mmol/dL", "L-3N", "m-3"),
        new CommonUnit("mmol/d", null),
        new CommonUnit("mmol/{ejaculate}", null),
        new CommonUnit("mmol/g{creat}", null),
        new CommonUnit("mmol/g", "M-1N"),
        new CommonUnit("mmol/h/mg{Hb}", null),
        new CommonUnit("mmol/h/mg{prot}", null),
        new CommonUnit("mmol/h", null),
        new CommonUnit("mmol/kg/(8.h)", null),
        new CommonUnit("mmol/kg/d", null),
        new CommonUnit("mmol/kg/h", null),
        new CommonUnit("mmol/kg", "M-1N"),
        new CommonUnit("mmol/kg/min", null),
        new CommonUnit("mmol/L", "L-3N", "m-3"),
        new CommonUnit("mmol/L{RBCs}", null),
        new CommonUnit("mmol/m2", "L-2N"),
        new CommonUnit("mmol/min", null),
        new CommonUnit("mmol/mmol{creat}", null),
        new CommonUnit("mmol/mmol", null),
        new CommonUnit("mmol/mmol{urea}", null),
        new CommonUnit("mmol/mol", "1"),
        new CommonUnit("mmol/mol{Cre}", "1"),
        new CommonUnit("mmol/mol{creat}", null),
        new CommonUnit("mmol", "N"),
        new CommonUnit("mmol/s/L", null),
        new CommonUnit("mmol/{specimen}", null),
        new CommonUnit("mmol/{total_vol}", null),
        new CommonUnit("mmol/{TotalVolume}", "N"),
        new CommonUnit("mol/kg", "M-1N"),
        new CommonUnit("mol/kg/s", null),
        new CommonUnit("mol/L", "L-3N", "m-3"),
        new CommonUnit("mol/m3", "L-3N", "m-3"),
        new CommonUnit("mol/mL", "L-3N", "m-3"),
        new CommonUnit("mol/mol", null),
        new CommonUnit("mol", "N"),
        new CommonUnit("mol/s", null),
        new CommonUnit("{M.o.M}", null),
        new CommonUnit("/mo", null),
        new CommonUnit("mosm/kg", "M-1N"),
        new CommonUnit("mosm/L", "L-3N", "m-3"),
        new CommonUnit("mosm", "N"),
        new CommonUnit("mo", "T", "s"),
        new CommonUnit("mPa", null),
        new CommonUnit("mPa.s", null),
        new CommonUnit("[MPL'U]/mL", null),
        new CommonUnit("[MPL'U]", null),
        new CommonUnit("{MPS'U}/mL", null),
        new CommonUnit("{MPS'U}", null),
        new CommonUnit("m/s2", null),
        new CommonUnit("m/s", null),
        new CommonUnit("ms", "T", "s"),
        new CommonUnit("Ms", "T", "s"),
        new CommonUnit("mU/g{Hb}", null),
        new CommonUnit("mU/g{Hgb}", "M-1T-1N"),
        new CommonUnit("mU/g", "M-1T-1N"),
        new CommonUnit("mU/g{prot}", null),
        new CommonUnit("mU/L", null),
        new CommonUnit("mU/mg{creat}", null),
        new CommonUnit("mU/mg{Cre}", "M-1T-1N"),
        new CommonUnit("mU/mg", "M-1T-1N"),
        new CommonUnit("mU/mL/min", null),
        new CommonUnit("mU/mL", null),
        new CommonUnit("mU/mmol{creat}", null),
        new CommonUnit("mU/mmol{RBCs}", null),
        new CommonUnit("{mutation}", null),
        new CommonUnit("mV", null),
        new CommonUnit("mV/s", null),
        new CommonUnit("N.cm", null),
        new CommonUnit("ng/10*6", null),
        new CommonUnit("ng/10*6{RBCs}", null),
        new CommonUnit("ng/(24.h)", null),
        new CommonUnit("ng/(8.h)", null),
        new CommonUnit("ng/dL", "L-3M", "g.m-3"),
        new CommonUnit("ng/d", null),
        new CommonUnit("ng{FEU}/mL", null),
        new CommonUnit("ng/g",	"1"),
        new CommonUnit("ng/g{Cre}", "1"),
        new CommonUnit("ng/g{creat}", null),
        new CommonUnit("ng/h", null),
        new CommonUnit("ng/kg", "1"),
        new CommonUnit("ng/kg/(8.h)", null),
        new CommonUnit("ng/kg/h", null),
        new CommonUnit("ng/kg/min", null),
        new CommonUnit("ng/L", "L-3M", "g.m-3"),
        new CommonUnit("ng/m2", "L-2M", "g.m-2"),
        new CommonUnit("ng", "M", "g"),
        new CommonUnit("ng/mg", "1"),
        new CommonUnit("ng/mg{creat}", null),
        new CommonUnit("ng/mg/h", null),
        new CommonUnit("ng/mg{Protein}", "1"),
        new CommonUnit("ng/mg{prot}", null),
        new CommonUnit("ng/min", null),
        new CommonUnit("ng/mL/h", null),
        new CommonUnit("ng/mL", "L-3M", "g.m-3"),
        new CommonUnit("ng/mL{rbc}", "L-3M", "g.m-3"),
        new CommonUnit("ng/mL{RBCs}", null),
        new CommonUnit("ng/s", null),
        new CommonUnit("ng/U", null),
        new CommonUnit("nkat", null),
        new CommonUnit("nL", "L3", "m3"),
        new CommonUnit("[nmi_i]", "L", "m"),
        new CommonUnit("nm", "L", "m"),
        new CommonUnit("nmol/(24.h)", null),
        new CommonUnit("nmol{ATP}", null),
        new CommonUnit("nmol{BCE}/L", null),
        new CommonUnit("nmol{BCE}", null),
        new CommonUnit("nmol/dL{GF}", null),
        new CommonUnit("nmol/dL", "L-3N", "m-3"),
        new CommonUnit("nmol/d", null),
        new CommonUnit("nmol/g{creat}", null),
        new CommonUnit("nmol/g{Cre}", "M-1N"),
        new CommonUnit("nmol/g{dry_wt}", null),
        new CommonUnit("nmol/g", "M-1N"),
        new CommonUnit("nmol/h/L", null),
        new CommonUnit("nmol/h/mg{prot}", null),
        new CommonUnit("nmol/h/mL", null),
        new CommonUnit("nmol/L", "L-3N", "m-3"),
        new CommonUnit("nmol/L/mmol{creat}", null),
        new CommonUnit("nmol/L{RBCs}", null),
        new CommonUnit("nmol/mg{creat}", null),
        new CommonUnit("nmol/mg/h", null),
        new CommonUnit("nmol/mg", "M-1N"),
        new CommonUnit("nmol/mg{prot}/h", null),
        new CommonUnit("nmol/mg{prot}", null),
        new CommonUnit("nmol/min/10*6{cells}", null),
        new CommonUnit("nmol/min/mg{Hb}", null),
        new CommonUnit("nmol/min/mg{protein}", null),
        new CommonUnit("nmol/min/mg{prot}", null),
        new CommonUnit("nmol/min/mL", null),
        new CommonUnit("nmol/min", null),
        new CommonUnit("nmol/mL/h", null),
        new CommonUnit("nmol/mL", "L-3N", "m-3"),
        new CommonUnit("nmol/mL/min", null),
        new CommonUnit("nmol/m/mg{prot}", null),
        new CommonUnit("nmol/mmol", "1"),
        new CommonUnit("nmol/mmol{Cre}", "1"),
        new CommonUnit("nmol/mmol{creat}", null),
        new CommonUnit("nmol/mol", "1"),
        new CommonUnit("nmol/mol{creat}", null),
        new CommonUnit("nmol", "N"),
        new CommonUnit("nmol/nmol", null),
        new CommonUnit("nmol/s/L", null),
        new CommonUnit("nmol/s", null),
        new CommonUnit("nmol/umol{creat}", null),
        new CommonUnit("nm/s/L", null),
        new CommonUnit("N", null),
        new CommonUnit("%{Normal}", "1"),
        new CommonUnit("%{normal}", null),
        new CommonUnit("%{NormalPooledPlasma}", "1"),
        new CommonUnit("N.s", null),
        new CommonUnit("ns", "T", "s"),
        new CommonUnit("{#}", null),
        new CommonUnit("nU/mL", null),
        new CommonUnit("nU/{RBC}", null),
        new CommonUnit("{OD_unit}", null),
        new CommonUnit("%{ofBacteria}", "1"),
        new CommonUnit("%{OfLymphocytes}", "1"),
        new CommonUnit("%{OfWBCs}", "1"),
        new CommonUnit("Ohm.m", null),
        new CommonUnit("Ohm", null),
        new CommonUnit("/{OIF}", null),
        new CommonUnit("osm/kg", "M-1N"),
        new CommonUnit("osm/L", "L-3N", "m-3"),
        new CommonUnit("osm", null),
        new CommonUnit("%{Oxygen}", "1"),
        new CommonUnit("[oz_av]", "M", "g"),
        new CommonUnit("[oz_tr]", "M", "g"),
        new CommonUnit("{Pan_Bio'U}", null),
        new CommonUnit("pA", null),
        new CommonUnit("Pa", null),
        new CommonUnit("%{penetration}", null),
        new CommonUnit("{percentile}", null),
        new CommonUnit("pg/{cell}", null),
        new CommonUnit("pg/dL", "L-3M", "g.m-3"),
        new CommonUnit("pg/L", "L-3M", "g.m-3"),
        new CommonUnit("pg", "M","g"),
        new CommonUnit("pg/mg{creat}", null),
        new CommonUnit("pg/mg", null),
        new CommonUnit("pg/mL", "L-3M", "g.m-3"),
        new CommonUnit("pg/mL{sLT}", null),
        new CommonUnit("pg/mm", "L-1M"),
        new CommonUnit("pg/{RBC}", null),
        new CommonUnit("{phenotype}", null),
        new CommonUnit("[pH]", "[pH]"),
        new CommonUnit("pkat", null),
        new CommonUnit("{#}/{platelet}", null),
        new CommonUnit("pL", "L3", "m3"),
        new CommonUnit("pm", "L", "m"),
        new CommonUnit("pmol/(24.h)", null),
        new CommonUnit("pmol/dL", "L-3N", "m-3"),
        new CommonUnit("pmol/d", null),
        new CommonUnit("pmol/g", null),
        new CommonUnit("pmol/H/mg{protein}", null),
        new CommonUnit("pmol/h/mg{prot}", null),
        new CommonUnit("pmol/h/mL", null),
        new CommonUnit("pmol/L", "L-3N", "m-3"),
        new CommonUnit("pmol/mg{prot}", null),
        new CommonUnit("pmol/min/mg{prot}", null),
        new CommonUnit("pmol/min", null),
        new CommonUnit("pmol/mL", "L-3N", "m-3"),
        new CommonUnit("pmol/mmol{creat}", null),
        new CommonUnit("pmol", "N"),
        new CommonUnit("pmol/{RBC}", null),
        new CommonUnit("pmol/umol", "1"),
        new CommonUnit("pmol/umol{creat}", null),
        new CommonUnit("%{pooled_plasma}", null),
        new CommonUnit("%{Positive}", "1"),
        new CommonUnit("%{positive}", null),
        new CommonUnit("[ppb]", null),
        new CommonUnit("[ppm]", null),
        new CommonUnit("[ppm]{v/v}", null),
        new CommonUnit("[ppth]", null),
        new CommonUnit("[pptr]", null),
        new CommonUnit("[psi]", null),
        new CommonUnit("ps", "T", "s"),
        new CommonUnit("pT", null),
        new CommonUnit("[pt_us]", "L3", "m3"),
        new CommonUnit("[qt_us]", "L3", "m3"),
        new CommonUnit("{ratio}", null),
        new CommonUnit("%{RBCs}", null),
        new CommonUnit("{rbc}/uL", "L-3", "m-3"),
        new CommonUnit("{RBC}/uL", null),
        new CommonUnit("%{reactive}", null),
        new CommonUnit("%{recovery}", null),
        new CommonUnit("%{reference}", null),
        new CommonUnit("%{Relative}", "1"),
        new CommonUnit("%{relative}", null),
        new CommonUnit("{rel_saturation}", null),
        new CommonUnit("%{residual}", null),
        new CommonUnit("%{response}", null),
        new CommonUnit("{risk}", null),
        new CommonUnit("{Rubella_virus}", null),
        new CommonUnit("%{saturation}", null),
        new CommonUnit("{saturation}", null),
        new CommonUnit("s/{control}", null),
        new CommonUnit("{s_co_ratio}", null),
        new CommonUnit("{score}", null),
        new CommonUnit("[sft_i]", "L2", "m2"),
        new CommonUnit("{shift}", null),
        new CommonUnit("[sin_i]", "L2", "m2"),
        new CommonUnit("/s", null),
        new CommonUnit("S", null),
        new CommonUnit("{Spermatozoa}/mL", "L-6", "m-3"),
        new CommonUnit("{spermatozoa}/mL", null),
        new CommonUnit("%{SpermMotility}", "1"),
        new CommonUnit("s", "T", "s"),
        new CommonUnit("{STDV}", null),
        new CommonUnit("[ston_av]", "M", "g"),
        new CommonUnit("Sv", null),
        new CommonUnit("[syd_i]", "L2", "m2"),
        new CommonUnit("[tbs_us]", null),
        new CommonUnit("[tb'U]", null),
        new CommonUnit("{titer}", null),
        new CommonUnit("t", "M", "g"),
        new CommonUnit("{TmStp}", null),
        new CommonUnit("T", null),
        new CommonUnit("[todd'U]", null),
        new CommonUnit("/{tot}", "1"),
        new CommonUnit("%{Total}", "1"),
        new CommonUnit("%{total}", null),
        new CommonUnit("%{TotalProtein}", "1"),
        new CommonUnit("{Tscore}", null),
        new CommonUnit("{TSI_index}", null),
        new CommonUnit("[tsp_us]", null),
        new CommonUnit("U/10*10{cells}", null),
        new CommonUnit("U/10*10", null),
        new CommonUnit("U/10*12", null),
        new CommonUnit("U/10*12{RBCs}", null),
        new CommonUnit("U/10*6", null),
        new CommonUnit("U/10*9", null),
        new CommonUnit("U/(10.g){feces}", null),
        new CommonUnit("U/10", null),
        new CommonUnit("U/(12.h)", null),
        new CommonUnit("U/(24.h)", null),
        new CommonUnit("U{25Cel}/L", null),
        new CommonUnit("U/(2.h)", null),
        new CommonUnit("U{37Cel}/L", null),
        new CommonUnit("U{ComplementCh50}/mL", "L-3[arb]", "m-3.s-1"),
        new CommonUnit("U/dL", null),
        new CommonUnit("U/d", null),
        new CommonUnit("ueq/L", "L-3N", "m-3"),
        new CommonUnit("ueq/mL", "L-3N", "m-3"),
        new CommonUnit("ueq", "N"),
        new CommonUnit("ug/(100.g)", null),
        new CommonUnit("ug/(24.h)", null),
        new CommonUnit("ug/(8.h)", null),
        new CommonUnit("U/g{creat}", null),
        new CommonUnit("U/g{Cre}", "M-1T-1N"),
        new CommonUnit("ug/dL", "L-3M", "g.m-3"),
        new CommonUnit("ug/dL{rbc}", "L-3M", "g.m-3"),
        new CommonUnit("ug/dL{RBCs}", null),
        new CommonUnit("ug/d", null),
        new CommonUnit("ug{FEU}/mL", null),
        new CommonUnit("ug/g", "1"),
        new CommonUnit("ug/g{Cre}", "1"),
        new CommonUnit("ug/g{creat}", null),
        new CommonUnit("ug/g{dry_tissue}", null),
        new CommonUnit("ug/g{DryWeight}", "1"),
        new CommonUnit("ug/g{dry_wt}", null),
        new CommonUnit("ug/g{feces}", null),
        new CommonUnit("ug/g{hair}", null),
        new CommonUnit("ug/g{Hb}", null),
        new CommonUnit("ug/g{Hgb}", "1"),
        new CommonUnit("ug/g{tissue}", null),
        new CommonUnit("U/g{Hb}", null),
        new CommonUnit("U/g{Hgb}", "M-1T-1N"),
        new CommonUnit("ug/h", null),
        new CommonUnit("ug/kg", "1"),
        new CommonUnit("ug/kg/(8.h)", null),
        new CommonUnit("ug/kg/d", null),
        new CommonUnit("ug/kg/h", null),
        new CommonUnit("ug/kg/min", null),
        new CommonUnit("ug/L/(24.h)", null),
        new CommonUnit("ug/L", "L-3M", "g.m-3"),
        new CommonUnit("ug/L{RBCs}", null),
        new CommonUnit("U/g", "M-1T-1N"),
        new CommonUnit("ug/m2", "L-2M", "g.m-2"),
        new CommonUnit("ug/m3", null),
        new CommonUnit("ug", "M", "g"),
        new CommonUnit("ug/mg", "1"),
        new CommonUnit("ug/mg{Cre}", "1"),
        new CommonUnit("ug/mg{creat}", null),
        new CommonUnit("ug/min", null),
        new CommonUnit("ug/mL{class}", null),
        new CommonUnit("ug/mL{eqv}", null),
        new CommonUnit("ug/mL", "L-3M", "g.m-3"),
        new CommonUnit("ug/mmol{creat}", null),
        new CommonUnit("ug/mmol", null),
        new CommonUnit("ug/ng", "1"),
        new CommonUnit("U/g{protein}", null),
        new CommonUnit("ug/[sft_i]", null),
        new CommonUnit("ug/{Specimen}", "M", "g"),
        new CommonUnit("ug/{specimen}", null),
        new CommonUnit("ug/{TotalVolume}", "M", "g"),
        new CommonUnit("U/h", null),
        new CommonUnit("U{IgAPhospholipid}/mL", "L-3[arb]", "m-3.s-1"),
        new CommonUnit("U{IgGPhospholipid}/mL", "L-3[arb]", "m-3.s-1"),
        new CommonUnit("U{IgMPhospholipid}/mL", "L-3[arb]", "m-3.s-1"),
        new CommonUnit("u[iU]", "[arb]"),
        new CommonUnit("u[IU]/L", null),
        new CommonUnit("u[iU]/mL", "L-3[arb]", "m-3"),
        new CommonUnit("u[IU]/mL", null),
        new CommonUnit("ukat", null),
        new CommonUnit("U/kg{Hb}", null),
        new CommonUnit("uL/(2.h)", null),
        new CommonUnit("uL/h", null),
        new CommonUnit("U/L", "L-3[arb]", "m-3.s-1"),
        new CommonUnit("/uL", "L-3", "m-3"),
        new CommonUnit("uL", "L3", "m3"),
        new CommonUnit("{#}/uL", null),
        new CommonUnit("U/min", null),
        new CommonUnit("um", "L", "m"),
        new CommonUnit("U/mL", null),
        new CommonUnit("U/mL{RBCs}", null),
        new CommonUnit("U/mmol{creat}", null),
        new CommonUnit("umol/10*6{RBC}", null),
        new CommonUnit("umol/(24.h)", null),
        new CommonUnit("umol/(2.h)", null),
        new CommonUnit("umol/(8.h)", null),
        new CommonUnit("umol{BCE}/mol", null),
        new CommonUnit("umol/dL{GF}", null),
        new CommonUnit("umol/dL", "L-3N", "m-3"),
        new CommonUnit("umol/d", null),
        new CommonUnit("umol/g{creat}", null),
        new CommonUnit("umol/g{Cre}", "M-1N"),
        new CommonUnit("umol/g{Hb}", null),
        new CommonUnit("umol/g{Hgb}", "M-1N"),
        new CommonUnit("umol/g", "M-1N"),
        new CommonUnit("umol/h", null),
        new CommonUnit("umol/kg{feces}", null),
        new CommonUnit("umol/kg", null),
        new CommonUnit("umol/L/h", null),
        new CommonUnit("umol/L", "L-3N", "m-3"),
        new CommonUnit("umol/L{RBCs}", null),
        new CommonUnit("umol/mg{creat}", null),
        new CommonUnit("umol/mg{Cre}", "M-1N"),
        new CommonUnit("umol/mg", "M-1N"),
        new CommonUnit("umol/min/g", "M-1T-1N"),
        new CommonUnit("umol/min/g{mucosa}", null),
        new CommonUnit("umol/min/g{prot}", null),
        new CommonUnit("umol/min/L", null),
        new CommonUnit("umol/min", null),
        new CommonUnit("umol/mL", "L-3N", "m-3"),
        new CommonUnit("umol/mL/min", null),
        new CommonUnit("umol/mmol{creat}", null),
        new CommonUnit("umol/mmol", null),
        new CommonUnit("umol/mol", "1"),
        new CommonUnit("umol/mol{Cre}", "1"),
        new CommonUnit("umol/mol{creat}", null),
        new CommonUnit("umol/mol{Hb}", null),
        new CommonUnit("umol", "N"),
        new CommonUnit("umol/umol{creat}", null),
        new CommonUnit("umol/umol", null),
        new CommonUnit("um/s", null),
        new CommonUnit("/U", null),
        new CommonUnit("U", null),
        new CommonUnit("uOhm", null),
        new CommonUnit("%{Uptake}", "1"),
        new CommonUnit("%{uptake}", null),
        new CommonUnit("U/s", null),
        new CommonUnit("us", "T", "s"),
        new CommonUnit("uU/g", null),
        new CommonUnit("uU/L", null),
        new CommonUnit("uU/mL", null),
        new CommonUnit("uV", null),
        new CommonUnit("%{viable}", null),
        new CommonUnit("V", null),
        new CommonUnit("%{vol}", "1"),
        new CommonUnit("%{WBCs}", null),
        new CommonUnit("{WBCs}", null),
        new CommonUnit("Wb", null),
        new CommonUnit("/wk", null),
        new CommonUnit("{#}/wk", null),
        new CommonUnit("wk", "T", "s"),
        new CommonUnit("[yd_i]", "L", "m"),
        new CommonUnit("{yyyy}", null),
        new CommonUnit("{Zscore}", null)
    ));
}
